import { applyJerseyPlan } from "./applyPlan.js";
import { saveFingerprint, storePlan } from "./planStore.js";
import { jerseyTeams, loadJerseyTables, playerRowMap, teamNames, userControlledTeams } from "./shared.js";
import { displayClassYear, displayPosition } from "./core/logger.js";
import { runNoDuplicatesRoster } from "./core/noDuplicatesEngine.js";

const TOOL_ID = "jersey-no-duplicates", TOOL_NAME = "Jersey Renumber — No Duplicates";
const isPlaceholder = player => player.FirstName === "Omar" && player.LastName === "Omar" && player.Position === "QB" && Number(player.JerseyNum) === 0;
const isRostered = player => player && !player.isEmpty && Number(player.TeamIndex) >= 0 && Number(player.TeamIndex) !== 255 && !isPlaceholder(player);
const normalize = options => ({ skippedTeams: Array.isArray(options?.skippedTeams) ? options.skippedTeams.map(String) : [], enableTeamRules: options?.enableTeamRules !== false, enableRetiredNumbers: options?.enableRetiredNumbers !== false, enablePromotions: options?.enablePromotions !== false });
export async function prepareJerseyNoDuplicates({ savePath, schemaPath }) { const loaded = await loadJerseyTables(savePath, schemaPath, { franchiseUsers: true }); const names = teamNames(loaded.teams.records), controlled = userControlledTeams(loaded.teams, loaded.franchiseUsers, loaded.players); return { teams: jerseyTeams(loaded.teams.records), userControlledTeams: [...controlled].map(index => names.get(index)).filter(Boolean) }; }

async function preview(context) {
  const options = normalize(context.options); const loaded = await loadJerseyTables(context.savePath, context.schemaPath, { franchiseUsers: true }); const names = teamNames(loaded.teams.records); const rowMap = playerRowMap(loaded.players.records), skipped = new Set([...names].filter(([, name]) => options.skippedTeams.includes(name)).map(([index]) => index));
  const rosters = new Map(); for (const player of loaded.players.records) { if (!isRostered(player) || skipped.has(Number(player.TeamIndex)) || !names.has(Number(player.TeamIndex))) continue; player.originalJerseyNum = Number(player.JerseyNum); const index = Number(player.TeamIndex); if (!rosters.has(index)) rosters.set(index, []); rosters.get(index).push(player); }
  const allChanges = [], analytics = { players: 0, fallbacks: 0, wrFallbacks: 0, qbFallbacks: 0, duplicateResolutions: 0, promotions: 0, retiredCorrections: 0, positionCorrections: 0, teamRuleChanges: 0, nilChanges: 0 };
  for (const [teamIndex, roster] of [...rosters].sort((a, b) => (names.get(a[0]) ?? "").localeCompare(names.get(b[0]) ?? ""))) { const teamName = names.get(teamIndex) ?? `Team ${teamIndex}`; const result = runNoDuplicatesRoster(roster, teamName, options); analytics.players += roster.length; analytics.fallbacks += result.analytics.fallbackPlayers.length; analytics.wrFallbacks += result.analytics.wrFallbacks; analytics.qbFallbacks += result.analytics.qbFallbacks; for (const change of result.changes) { const item = { row: rowMap.get(change.player), team: teamName, player: `${change.player.FirstName} ${change.player.LastName}`.trim(), position: displayPosition(change.player.Position), classYear: displayClassYear(change.player), overall: change.player.OverallRating, nil: Boolean(change.player.IsNIL), oldNumber: change.oldNumber, newNumber: change.newNumber, reason: change.reason, fallback: change.fallback, duplicateWith: change.duplicateWith ? `${change.duplicateWith.FirstName} ${change.duplicateWith.LastName}`.trim() : null }; allChanges.push(item); if (change.player.IsNIL) analytics.nilChanges++; if (change.reason === "duplicate resolved") analytics.duplicateResolutions++; else if (change.reason === "promotion") analytics.promotions++; else if (change.reason === "retired number protected") analytics.retiredCorrections++; else if (change.reason === "position range corrected") analytics.positionCorrections++; else analytics.teamRuleChanges++; } }
  const assignments = allChanges.map(change => ({ row: change.row, oldNumber: Number(change.oldNumber), newNumber: Number(change.newNumber) })); const result = { status: "preview", mode: "preview", savePath: loaded.savePath, backupPath: null, reportPath: null, summary: [{ label: "Players allocated", value: analytics.players }, { label: "Players changed", value: allChanges.length }, { label: "Duplicate resolutions", value: analytics.duplicateResolutions }, { label: "Fallback assignments", value: analytics.fallbacks }], historySummary: [{ label: "Players changed", value: allChanges.length }, { label: "Duplicate resolutions", value: analytics.duplicateResolutions }], resultKind: TOOL_ID, details: { ...analytics, totalPreviewRows: allChanges.length, changes: allChanges.slice(0, 1000) } };
  const report = { prefix: "jersey-no-duplicates-report", headings: ["Team", "Player", "Position", "Class", "Overall", "NIL", "OldNumber", "NewNumber", "Reason", "Fallback"], rows: allChanges.map(change => [change.team, change.player, change.position, change.classYear, change.overall, change.nil, change.oldNumber, change.newNumber, change.reason, change.fallback]) }; result.reportPath = context.reports.create({ ...report, toolId: TOOL_ID, toolName: TOOL_NAME }); const planId = storePlan({ toolId: TOOL_ID, toolName: TOOL_NAME, savePath: loaded.savePath, saveFingerprint: saveFingerprint(loaded.savePath), assignments, previewRows: allChanges, report, result, backupWhenEmpty: false });
  return { ...result, planId };
}
export async function runJerseyNoDuplicates(context) { if (context.mode === "apply") return applyJerseyPlan({ ...context, toolId: TOOL_ID }); if (context.mode !== "preview") throw new Error("Run mode must be preview or apply."); return preview(context); }
