import { applyJerseyPlan } from "./applyPlan.js";
import { saveFingerprint, storePlan } from "./planStore.js";
import { DEFENSE, OFFENSE, SPECIALISTS, jerseyTeams, loadJerseyTables, playerRowMap, teamNames, userControlledTeams } from "./shared.js";
import { shouldProcess } from "./core/playerFilter.js";
import { sortRoster } from "./core/playerSorter.js";
import { isAllowedExistingDuplicate, resolveDuplicates } from "./core/duplicateResolver.js";
import { runRenumberEngine } from "./core/renumberEngine.js";
import { countTopThreeQbDuplicateConflicts, validateRoster } from "./core/validator.js";
import { validateAppliedTeamRules } from "./core/teamRules.js";
import { displayPosition } from "./core/logger.js";

const TOOL_ID = "jersey-renumber";
const TOOL_NAME = "Jersey Renumber";
const classLabel = player => `${String(player.RedshirtStatus ?? "").toLowerCase() === "previous" ? "RS " : ""}${String(player.SchoolYear ?? "Unknown")}`;
const normalize = options => ({ skippedTeams: Array.isArray(options?.skippedTeams) ? options.skippedTeams.map(String) : [], renumberNilPlayers: Boolean(options?.renumberNilPlayers), enableTeamRules: options?.enableTeamRules !== false, enableRetiredNumbers: options?.enableRetiredNumbers !== false, enablePromotions: options?.enablePromotions !== false });
const sortAndResolve = groups => { for (const team of groups.values()) for (const roster of [team.offense, team.defense, team.specialists]) { sortRoster(roster); resolveDuplicates(roster); } };

function validation(groups, names, enableTeamRules) {
  let duplicateCount = 0, unchangedCount = 0, topThreeQbDuplicateCount = 0; const fallbackPlayers = [], protectedNilFallbackPlayers = [], protectedNilDuplicates = [];
  for (const [teamIndex, team] of groups) { const teamName = names.get(teamIndex) ?? `Team ${teamIndex}`; for (const [side, roster] of [["Offense", team.offense], ["Defense", team.defense], ["Special Teams", team.specialists]]) { const result = validateRoster(teamName, side, roster); duplicateCount += result.duplicates; unchangedCount += result.suboptimal; fallbackPlayers.push(...result.fallbackPlayers.map(player => ({ teamName, side, player }))); protectedNilFallbackPlayers.push(...result.protectedNilFallbackPlayers); protectedNilDuplicates.push(...result.protectedNilDuplicates.map(group => ({ teamName, side, ...group }))); } topThreeQbDuplicateCount += countTopThreeQbDuplicateConflicts(team.offense); }
  return { duplicateCount, unchangedCount, topThreeQbDuplicateCount, fallbackPlayers, protectedNilFallbackPlayers, protectedNilDuplicates, teamRuleViolationCount: enableTeamRules ? validateAppliedTeamRules(groups, names) : 0 };
}
function permittedDuplicates(groups) { let count = 0; for (const team of groups.values()) { const byNumber = new Map(); for (const player of team.offense) { const holders = byNumber.get(player.JerseyNum) ?? []; holders.push(player); byNumber.set(player.JerseyNum, holders); } for (const holders of byNumber.values()) if (holders.length === 2 && isAllowedExistingDuplicate(holders[0], holders[1], team.offense)) count++; } return count; }

export async function prepareJerseyRenumber({ savePath, schemaPath }) { const loaded = await loadJerseyTables(savePath, schemaPath, { franchiseUsers: true }); const names = teamNames(loaded.teams.records); const controlled = userControlledTeams(loaded.teams, loaded.franchiseUsers, loaded.players); return { teams: jerseyTeams(loaded.teams.records), userControlledTeams: [...controlled].map(teamIndex => ({ teamIndex, name: names.get(teamIndex) ?? `Team ${teamIndex}` })).sort((a, b) => a.name.localeCompare(b.name)) }; }

async function preview(context) {
  const options = normalize(context.options); const loaded = await loadJerseyTables(context.savePath, context.schemaPath, { franchiseUsers: true }); const names = teamNames(loaded.teams.records); const skipped = new Set([...names].filter(([, name]) => options.skippedTeams.includes(name)).map(([index]) => index)); const rows = playerRowMap(loaded.players.records);
  for (const player of loaded.players.records) { if (!player) continue; player.wasRenumberedThisRun = false; player.teamRuleLocked = false; player.teamRuleNumber = undefined; player.teamRuleSide = undefined; player.teamRuleLabel = undefined; player.mandatoryJerseyRelocation = undefined; player.freshmanReleasedNumber = undefined; player.teamReservedNumbers = new Set(); player.nilRenumberAllowed = options.renumberNilPlayers; player.originalJerseyNum = player.JerseyNum; }
  const sortedTeams = loaded.teams.records.filter(team => team && !team.isEmpty && names.has(Number(team.TeamIndex))).sort((a, b) => String(a.DisplayName ?? "").localeCompare(String(b.DisplayName ?? ""))).map(team => Number(team.TeamIndex));
  const rosters = new Map(sortedTeams.filter(index => !skipped.has(index)).map(index => [index, []])); for (const player of loaded.players.records) { if (!shouldProcess(player) || skipped.has(Number(player.TeamIndex))) continue; rosters.get(Number(player.TeamIndex))?.push(player); }
  const groups = new Map(); for (const [index, roster] of rosters) { const team = { offense: [], defense: [], specialists: [] }; for (const player of roster) { if (SPECIALISTS.has(player.Position)) team.specialists.push(player); else if (OFFENSE.has(player.Position)) team.offense.push(player); else if (DEFENSE.has(player.Position)) team.defense.push(player); } groups.set(index, team); }
  sortAndResolve(groups); const { stats, initialSuboptimal } = runRenumberEngine(groups, names, options); sortAndResolve(groups); const checked = validation(groups, names, options.enableTeamRules); const assignments = loaded.players.records.filter(player => player && !player.isEmpty && player.originalJerseyNum !== player.JerseyNum).map(player => ({ row: rows.get(player), oldNumber: Number(player.originalJerseyNum), newNumber: Number(player.JerseyNum), team: names.get(Number(player.TeamIndex)) ?? `Team ${player.TeamIndex}`, player: `${player.FirstName ?? ""} ${player.LastName ?? ""}`.trim(), position: displayPosition(player.Position), classYear: classLabel(player), overall: Number(player.OverallRating ?? 0), nil: Boolean(player.IsNIL) ? "Yes" : "No", reason: player.assignmentReason ?? player.teamRuleLabel ?? "allocation rule", fallback: player.assignmentFallback ? "True" : "False" })).sort((a, b) => a.team.localeCompare(b.team) || a.player.localeCompare(b.player) || a.position.localeCompare(b.position) || a.row - b.row);
  if (assignments.some(change => !Number.isInteger(change.newNumber) || change.newNumber < 0 || change.newNumber > 99)) throw new Error("Jersey allocation produced an invalid number. No plan was created.");
  const details = { ...stats, initialSuboptimal, totalPreviewRows: assignments.length, permittedDuplicateGroups: permittedDuplicates(groups), validation: { duplicateCount: checked.duplicateCount, unchangedCount: checked.unchangedCount, topThreeQbDuplicateCount: checked.topThreeQbDuplicateCount, teamRuleViolationCount: checked.teamRuleViolationCount, fallbackPlayers: checked.fallbackPlayers.length, protectedNilFallbackPlayers: checked.protectedNilFallbackPlayers.length, protectedNilDuplicateGroups: checked.protectedNilDuplicates.length }, changes: assignments.slice(0, 1000) };
  const result = { status: "preview", mode: "preview", savePath: loaded.savePath, backupPath: null, reportPath: null, summary: [{ label: "Players changed", value: assignments.length }, { label: "Duplicate resolutions", value: stats.duplicateResolutions }, { label: "Promotions", value: stats.promotions }, { label: "Fallback assignments", value: stats.fallbackAssignments }], historySummary: [{ label: "Players changed", value: assignments.length }, { label: "Duplicate resolutions", value: stats.duplicateResolutions }], resultKind: TOOL_ID, details };
  const report = { prefix: "jersey-renumber-report", headings: ["Team", "Player", "Position", "Class", "Overall", "NIL", "OldNumber", "NewNumber", "Reason", "Fallback"], rows: assignments.map(change => [change.team, change.player, change.position, change.classYear, change.overall, change.nil, change.oldNumber, change.newNumber, change.reason, change.fallback]) }; result.reportPath = context.reports.create({ ...report, toolId: TOOL_ID, toolName: TOOL_NAME }); const planId = storePlan({ toolId: TOOL_ID, toolName: TOOL_NAME, savePath: loaded.savePath, saveFingerprint: saveFingerprint(loaded.savePath), assignments, previewRows: assignments, report, result, backupWhenEmpty: true });
  return { ...result, planId };
}
export async function runJerseyRenumber(context) { if (context.mode === "apply") return applyJerseyPlan({ ...context, toolId: TOOL_ID }); if (context.mode !== "preview") throw new Error("Run mode must be preview or apply."); return preview(context); }
