export const categories = Object.freeze([
  { id: "appearance", name: "Player Appearance & Identity", order: 10 },
  { id: "ratings", name: "Ratings & Team Tuning", order: 20 },
  { id: "dynasty", name: "Dynasty Management", order: 30 }
]);

const activeSave = Object.freeze({ mode: "active-direct", required: true, accepted: ["dynasty", "road-to-glory"] });
export const tools = Object.freeze([
  { id: "nil-toggle", name: "NIL Toggle", shortName: "NIL Toggle", category: "ratings", version: "1.0", icon: "⇄", description: "Turns the NIL flag on or off for selected players or active rosters. Run whenever you need to change in-game editing eligibility; this does not identify real-life NIL players.", input: activeSave, status: "available", preview: true, reports: ["csv"] },
  { id: "jersey-renumber", name: "Jersey Renumber", shortName: "Jersey Renumber", category: "appearance", version: "4.0", icon: "#", description: "Assigns realistic jersey numbers while respecting roster rules and team traditions. Best run once each preseason.", input: activeSave, status: "available", preview: true, reports: ["csv"] },
  { id: "jersey-no-duplicates", name: "Jersey Renumber — No Duplicates", shortName: "No Duplicates", category: "appearance", version: "4.0", icon: "≠", description: "Assigns one unique jersey number to every player on each selected team. Best run once each preseason.", input: activeSave, status: "available", hidden: true, preview: true, reports: ["csv"] },
  { id: "commentary-id", name: "Commentary ID Patcher", shortName: "Commentary IDs", category: "appearance", version: "1.7", icon: "microphone", description: "Matches roster names to in-game commentary IDs. Best run once each preseason after new players arrive.", input: activeSave, status: "available", preview: true, reports: ["csv"], workflow: "review", settings: [{ id: "phonetic", type: "boolean", default: true }, { id: "firstName", type: "boolean", default: true }, { id: "preserveUnmatched", type: "boolean", default: true }, { id: "freshmenOnly", type: "boolean", default: true }, { id: "showAll", type: "boolean", default: false }] },
  { id: "freshman-equipment", name: "Equipment Randomizer", shortName: "Equipment Randomizer", category: "appearance", version: "5.0", icon: "shuffle", description: "Copies realistic equipment combinations from eligible donors. Best run once each preseason, before Equipment Patcher.", input: activeSave, status: "available", preview: true, reports: ["csv"] },
  { id: "equipment-patcher", name: "Equipment Patcher", shortName: "Equipment Patcher", category: "appearance", version: "5.0", icon: "shoulder-pads", description: "Cleans up common equipment issues. Best run once each preseason and recommended after running Equipment Randomizer.", input: activeSave, status: "available", preview: true, reports: ["csv"] },
  { id: "long-snap", name: "Long Snap Rating Fixer", shortName: "Long Snap Fixer", category: "ratings", version: "1.2", icon: "long-snap", description: "Normalizes unrealistic Long Snap ratings. Best run after training results, but it can be run anytime.", input: activeSave, status: "available", preview: true, reports: ["csv"] },
  { id: "team-boost", name: "Team Boost", shortName: "Team Boost", category: "ratings", version: "2.0", icon: "+", description: "Raises or lowers relevant player ratings. Best run after training results, but it can be run anytime.", input: activeSave, status: "available", preview: true, reports: ["csv"], settings: [{ id: "team", type: "team", required: true }, { id: "minimum", type: "integer", minimum: -99, maximum: 99, default: 1 }, { id: "maximum", type: "integer", minimum: -99, maximum: 99, default: 3 }, { id: "ratingMode", type: "select", default: "nonphysical", values: ["nonphysical", "all", "physical", "specific"] }] },
  { id: "dealbreaker-fixer", name: "Dealbreaker Fixer", shortName: "Dealbreaker Fixer", category: "dynasty", version: "1.0", icon: "handshake", description: "Replaces invalid player dealbreakers using roster context. Run whenever you need to clean up dealbreakers.", input: activeSave, status: "available", preview: true, reports: ["csv"] },
  { id: "automatic-force-win", name: "Smart Force Win", shortName: "Smart Force Win", category: "dynasty", version: "4.0", icon: "referee", description: "Calculates roster-based matchups and applies force wins. Best run in Week 0.", input: activeSave, status: "available", preview: true, reports: ["csv"] }
]);
export function getTool(id) { return tools.find(tool => tool.id === id) ?? null; }
export function registrySnapshot() { return { categories, tools }; }
