import path from "node:path";
import { createBackup } from "../../services/files.js";
import { openCfb27Save, readTables, PLAYER_TABLE_UID, TEAM_TABLE_UID } from "../../services/save.js";
import { mulberry32, patchLongSnapRatings, summarizeDistribution } from "./core.js";
import { completePlan, saveFingerprint, storePlan, takePlan } from "../jersey/planStore.js";
const teamNamesFrom=records=>{const names=new Map();records.forEach((r,row)=>{if(!r||r.isEmpty)return;const name=String(r.DisplayName||r.LongName||r.ShortName||`Team ${row}`),index=Number(r.TeamIndex);if(Number.isInteger(index))names.set(index,name);});return names;};
export async function runLongSnap({savePath,mode,options={},schemaPath,reports}){
 if(!["preview","apply"].includes(mode))throw new Error("Run mode must be preview or apply.");
 if(mode==="apply"){const plan=takePlan(options.planId);if(plan.toolId!=="long-snap"||path.resolve(plan.savePath)!==path.resolve(savePath))throw new Error("The preview does not belong to Long Snap Rating Fixer and this Active Save.");if(saveFingerprint(savePath)!==plan.saveFingerprint)throw new Error("The save changed after Preview. Run Preview again before Apply.");const opened=await openCfb27Save(savePath,schemaPath),{players}=await readTables(opened.franchise,{players:PLAYER_TABLE_UID});for(const c of plan.assignments){const r=players.records[c.row];if(!r||r.isEmpty||Number(r.LongSnapRating)!==Number(c.oldRating))throw new Error(`Player row ${c.row} changed after Preview. Run Preview again.`);}const reportPath=reports.create(plan.report);let backupPath=null;if(plan.assignments.length){backupPath=createBackup(savePath);for(const c of plan.assignments)players.records[c.row].LongSnapRating=c.newRating;await opened.franchise.save();}completePlan(options.planId);return{...plan.result,status:plan.assignments.length?"completed":"no-changes",mode,backupPath,reportPath};}
 const opened=await openCfb27Save(savePath,schemaPath),{players,teams}=await readTables(opened.franchise,{players:PLAYER_TABLE_UID,teams:TEAM_TABLE_UID});const sample=players.records.find(r=>r&&!r.isEmpty);if(!sample||sample.LongSnapRating===undefined||sample.Position===undefined||sample.TeamIndex===undefined)throw new Error("The player data does not expose the fields required by Long Snap Rating Fixer.");const seed=Math.floor(Math.random()*0x100000000),changes=patchLongSnapRatings(players.records,{random:mulberry32(seed)}),names=teamNamesFrom(teams.records),distribution=summarizeDistribution(changes);const rows=changes.map(c=>({row:c.row,team:names.get(c.teamIndex)??`Team ${c.teamIndex}`,player:`${c.record.FirstName??""} ${c.record.LastName??""}`.trim(),position:c.record.Position,overall:Number(c.record.OverallRating??0),oldRating:c.oldRating,newRating:c.newRating,reason:c.reason,changeType:c.kind})).sort((a,b)=>a.team.localeCompare(b.team)||a.player.localeCompare(b.player)||a.row-b.row);const report={toolId:"long-snap",toolName:"Long Snap Rating Fixer",prefix:"long-snap-ratings-report",headings:["Row","Team","Player","Position","Overall","OldRating","NewRating","Reason"],rows:rows.map(r=>[r.row,r.team,r.player,r.position,r.overall,r.oldRating,r.newRating,r.reason])};const reportPath=reports.create(report),result={status:"preview",mode,savePath:opened.savePath,backupPath:null,reportPath,summary:[{label:"Tight ends normalized",value:distribution.tightEnds},{label:"Offensive linemen normalized",value:distribution.offensiveLinemen},{label:"Players changed",value:distribution.count}],historySummary:[{label:"Players normalized",value:distribution.count}],resultKind:"long-snap",details:{seed,distribution,totalPreviewRows:rows.length,changes:rows.slice(0,1000)}};const assignments=changes.map(c=>({row:c.row,oldRating:c.oldRating,newRating:c.newRating}));return{...result,planId:storePlan({toolId:"long-snap",savePath,saveFingerprint:saveFingerprint(savePath),assignments,previewRows:rows,report,result})};}
