const { app, BrowserWindow, ipcMain } = require("electron");
const fs = require("node:fs"), os = require("node:os"), path = require("node:path"), { pathToFileURL } = require("node:url");
const root = path.resolve(__dirname, ".."), uiRoot = path.resolve(process.argv.find(arg => arg.startsWith("--ui-root="))?.slice(10) || root), temporary = fs.mkdtempSync(path.join(os.tmpdir(), "cfb-v180-ui-"));
app.setPath("userData", temporary); app.disableHardwareAcceleration();
app.whenReady().then(async () => {
  const { registrySnapshot } = await import(pathToFileURL(path.join(root, "src/shared/toolRegistry.js")));
  const { getToolHandler } = await import(pathToFileURL(path.join(root, "src/main/tools/handlers.js")));
  const fixture = path.resolve(root, "../EXAMPLE SAVES VANILLA GAME/DYNASTY-LSUTESTSAVEPRESZN"), schemaPath = path.join(root, "resources/engine-data/C27_486_6.gz");
  const cache = new Map(), runs = [];
  ipcMain.handle("app:bootstrap", () => ({ app: { version: "18.3", schemas: ["C27_486_6"] }, registry: registrySnapshot(), settings: { theme: "light", toolPresets: [] }, activeSave: { path: fixture, name: "UI Test", exists: true, schema: { version: "C27_486_6", supported: true } } }));
  ipcMain.handle("history:list", () => []);
  ipcMain.handle("updates:status", () => ({ phase: "disabled", message: "Update checks are disabled for this UI test." }));
  const games = Array.from({ length: 6 }, (_, row) => ({ row, week: row === 5 ? 4 : 5, homeTeam: row % 2 ? "Alabama" : "LSU", awayTeam: "Michigan", homeRank: row + 1, awayRank: 3, homeOverall: 92 - row, awayOverall: 90 - row, favorite: "LSU", underdog: "Michigan", favoriteSpread: -5.5, total: 52.5, favoriteMoneyline: -220, underdogMoneyline: 200 }));
  ipcMain.handle("home:lines", () => ({ season: 2026, modelProfile: "balanced", profiles: [{ value: "balanced", label: "Balanced" }], rows: games }));
  ipcMain.handle("home:context", () => ({ season: { season: 2026, week: 5, weekType: "RegularSeason" }, controlledTeams: [{ name: "LSU", nickname: "Tigers" }], teams: [{ name: "LSU" }], artwork: {} }));
  ipcMain.handle("tools:prepare", async (_event, request) => { if (!cache.has(request.toolId)) cache.set(request.toolId, await getToolHandler(request.toolId).prepare({ savePath: fixture, schemaPath })); return cache.get(request.toolId); });
  const result = request => ({ resultKind: request.toolId, mode: request.mode, status: request.mode === "preview" ? "preview" : "completed", planId: "ui-plan", reportPath: "UI-only mock report", backupPath: null, summary: [], details: { helmetBalance: request.toolId === "equipment-patcher" ? { fbs: { eligiblePlayers: 100, changes: 35, changesByTeam: { LSU: 4, Alabama: 3 }, families: [{ family: "SpeedFlex", before: 100, beforePercent: 100, after: 65, afterPercent: 65, targetCount: 65, targetPercent: 65 }] }, fcs: { eligiblePlayers: 0, families: [] } } : null, totalPreviewRows: 1, changes: [{ row: 0, team: "LSU", player: "Test Player", position: "QB", classYear: "Freshman", redshirtStatus: "Eligible", currentValue: false, proposedValue: true, changed: true, changes: [{ type: "helmet", currentValue: "Old", proposedValue: "New" }] }] } });
  ipcMain.handle("tools:run", (_event, request) => { runs.push(request); return result(request); });
  const window = new BrowserWindow({ show: false, width: 1480, height: 1000, webPreferences: { preload: path.join(uiRoot, "src/main/preload.cjs"), sandbox: true, contextIsolation: true, backgroundThrottling: false, offscreen: true } });
  await window.loadFile(path.join(uiRoot, "src/renderer/index.html"));
  const message = await window.webContents.executeJavaScript(`(async () => {
    const check = (value, message) => { if (!value) throw new Error(message); };
    const delay = () => new Promise(resolve => setTimeout(resolve, 50));
    const wait = async predicate => { for (let i = 0; i < 300; i++) { if (predicate()) { await delay(); return; } await delay(); } throw new Error("UI wait timed out"); };
    const change = (id, value) => { const node = document.querySelector(id); node.value = value; node.dispatchEvent(new Event("change", { bubbles: true })); };
    const pick = (id, values) => { const select = document.querySelector(id); for (const option of select.options) option.selected = values.includes(option.value); select.dispatchEvent(new Event("change", { bubbles: true })); };
    await wait(() => state.bootstrap);
    await refreshHomeContext(); navigate("home"); await wait(() => document.querySelectorAll(".home-matchup-card").length === 3);
    check(document.querySelector(".home-matchups h2").textContent === "Season Matchup Lines", "Prominent Home lines heading");
    check(document.querySelector(".home-matchups").textContent.includes("Week 5") && document.querySelector(".home-matchups").textContent.includes("MONEYLINE"), "Home uses active-week projections");
    check(notableWeekMatchups([{ row: 1, week: 5, homeRank: 40, awayRank: 40, homeOverall: 99, awayOverall: 99, favoriteSpread: -1 }, { row: 2, week: 5, homeRank: 1, awayRank: 2, homeOverall: 80, awayOverall: 80, favoriteSpread: -10 }], 5)[0].row === 2, "Ranked games take priority");
    navigate("equipment-patcher"); await wait(() => document.querySelector("#helmet-balance"));
    check(document.querySelector("#equipment-skip-nil").checked, "Fresh Patcher starts with Skip NIL enabled");
    for (const step of [1, 2, 3, 2, 1, 0]) { setEquipmentStep("equipment-patcher", step); await delay(); check(document.querySelector("#equipment-skip-nil").checked, "Skip NIL must survive every forward/back step"); }
    document.querySelector("#equipment-skip-nil").click(); document.querySelector("#helmet-allow-vicis").click(); document.querySelector("#helmet-balance").click(); document.querySelector("#fix-unlocked-mouthpieces").click(); document.querySelector("#randomize-existing-mouthpieces").click(); document.querySelector("#fix-unlocked-recolor").click();
    change("#mouthpiece-branded-frequency", "35"); change("#tape-color-mode", "accessory"); change("#unlocked-color-theme", "black"); change("#equipment-redshirt-group", "redshirt"); change("#equipment-min", "72"); pick("#equipment-positions", ["QB", "WR"]);
    check(document.querySelector("#tape-distribution-settings").hidden, "Match mode hides unused tape percentages");
    const configuration = JSON.stringify(equipmentOptions("equipment-patcher"));
    for (const step of [1, 2, 3, 0, 3]) { setEquipmentStep("equipment-patcher", step); await delay(); check(JSON.stringify(equipmentOptions("equipment-patcher")) === configuration, "Every Patcher control survives navigation"); }
    await runEquipment("equipment-patcher", "preview"); await delay();
    check(document.querySelector("#equipment-config-workspace").hidden && !document.querySelector("#equipment-preview-workspace").hidden, "Preview opens its own page");
    check(document.querySelector(".helmet-balance-preview")?.textContent.includes("100 (100.0%)") && document.querySelector(".helmet-balance-preview")?.textContent.includes("65 (65.0%)"), "Patcher Preview exposes before/after helmet counts and percentages");
    check(JSON.stringify(equipmentOptions("equipment-patcher")) === configuration, "Preview leaves configuration unchanged");
    await runEquipment("equipment-patcher", "apply"); await delay(); check(JSON.stringify(equipmentOptions("equipment-patcher")) === configuration, "Apply leaves configuration unchanged");
    navigate("long-snap"); navigate("equipment-patcher"); await wait(() => document.querySelector("#helmet-balance")); check(JSON.stringify(equipmentOptions("equipment-patcher")) === configuration, "Tool switching preserves all Patcher settings");
    document.querySelector("#reset-tool-defaults").click(); await wait(() => document.querySelector("#equipment-skip-nil"));
    check(document.querySelector("#equipment-skip-nil").checked && !document.querySelector("#helmet-balance").checked && !document.querySelector("#helmet-allow-vicis").checked, "Explicit Reset restores new defaults");
    navigate("team-boost"); await wait(() => document.querySelector("#boost-attributes"));
    change("#player-scope", "below-average"); pick("#boost-positions", ["QB", "WR", "TE"]); change("#rating-mode", "specific"); pick("#boost-attributes", ["SpeedRating", "AccelerationRating", "AgilityRating"]); pick("#team-search", [document.querySelector("#team-search").options[0].value]);
    check(!document.querySelector("#boost-attributes-field").hidden, "Specific Attributes exposes checkbox picker");
    const boost = JSON.stringify(collectOptions("team-boost")); navigate("long-snap"); navigate("team-boost"); await wait(() => document.querySelector("#boost-attributes")); check(JSON.stringify(collectOptions("team-boost")) === boost, "Team Boost combination survives tool switching");
    navigate("nil-toggle"); await wait(() => document.querySelector("#nil-target"));
    pick("#nil-positions", ["QB"]); pick("#nil-classes", ["Sophomore"]); pick("#nil-redshirts", ["Previous"]); pick("#nil-players", [document.querySelector("#nil-players").options[0].value]); change("#nil-target", "true");
    const nil = JSON.stringify(collectOptions("nil-toggle")); navigate("long-snap"); navigate("nil-toggle"); await wait(() => document.querySelector("#nil-target")); check(JSON.stringify(collectOptions("nil-toggle")) === nil, "NIL scope survives tool switching");
    await runTool("nil-toggle", "preview"); check(document.querySelector(".generic-player-card-list") && document.querySelector(".standard-config-workspace").hidden, "NIL preview uses a separate Cards page");
    document.querySelector('[data-generic-view="table"]').click(); check(!document.querySelector(".generic-player-table-view").hidden, "NIL Table view switches correctly");
    check(document.querySelector(".generic-player-table-view").textContent.includes("False") && document.querySelector(".generic-player-table-view").textContent.includes("True"), "NIL preview shows old and new flags");
    await runTool("nil-toggle", "apply"); check(JSON.stringify(collectOptions("nil-toggle")) === nil, "NIL Apply keeps scope configuration");
    check(!content.querySelector("select[multiple]:not([hidden])"), "All new multi-selects are mouse checkboxes");
    check(document.querySelector("#topbar-app-version").textContent === "v18.3", "Top version is correct");
    navigate("home"); await wait(() => document.querySelectorAll(".home-matchup-card").length === 3);
    return "Home top-three active-week lines, Patcher forward/back + Preview/Apply persistence, defaults/reset, Team Boost combinations, NIL Toggle Cards/Table, and session UI checks passed.";
  })()`);
  if (runs.length !== 4 || runs[1].options.planId !== "ui-plan" || runs[3].options.planId !== "ui-plan") throw new Error("Apply must use only the cached plan");
  await new Promise(resolve => setTimeout(resolve, 200));
  fs.mkdirSync(path.join(root, "outputs"), { recursive: true }); fs.writeFileSync(path.join(root, "outputs/v180-home-smoke.png"), (await window.webContents.capturePage()).toPNG());
  console.log(message); window.destroy(); app.quit();
}).catch(error => { console.error(error); app.exit(1); });
